services:
  stafl-devcontainer-iar:
    build:
      context: ./stafl-devcontainer-iar
      dockerfile: Dockerfile
      args:
        - BXARM=fs # change to fs for FuSa edition
    command: sleep infinity
    volumes:
      - ..:/workspaces:cached
      - LMS2:/usr/local/etc/IARSystems
    network_mode: host

volumes:
  LMS2:
    name: LMS2
